spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/kanban
    username: gardenkanban
    password: "12345"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE