CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tasks(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(30) CHECK (status IN ('NEW', 'DONE', 'IN_PROGRESS', 'REPEATED')),
    epic_id BIGINT,
    author_id BIGINT NOT NULL,
    assigned_to BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id),
    CONSTRAINT fk_epic_id FOREIGN KEY (epic_id) REFERENCES epics(id),
    CONSTRAINT fk_user_id FOREIGN KEY (author_id) REFERENCES users(id),
    CONSTRAINT fk_assigned_id FOREIGN KEY (assigned_to) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS epics(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_epic PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS boards(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner BIGINT NOT NULL,
    CONSTRAINT pk_board PRIMARY KEY (id),
    CONSTRAINT fk_user_id FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS board_collaborators(
    board_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (board_id, user_id),
    CONSTRAINT fk_board FOREIGN KEY (board_id) REFERENCES boards(id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);
